---
# Copyright (C) 2022 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
name: python
on:
  workflow_call:
    inputs:
      coveralls:
        description: |
          Upload test coverage data to coveralls.io when true.
        required: false
        type: boolean
        default: false
      mypy:
        description: Enables/disables the mypy job
        required: false
        type: boolean
        default: true
      docs:
        description: Enables/disables docs generation with sphinx
        required: false
        type: boolean
        default: true
      deb:
        description: Enables python-stdeb when true.
        required: false
        type: boolean
        default: false
      publish_pypi:
        description: Enables the publish-pypi job.
        required: false
        type: boolean
        default: true
      publish_github_release:
        description: Enables the publish-github-release job.
        required: false
        type: boolean
        default: true
      publish_github_release_files:
        description: Files to publish in the github release.
        required: false
        type: string
        default: ''
      publish_packagecloud:
        description: Enables the publish-packagecloud job.
        required: false
        type: boolean
        default: false
      publish_packagecloud_repository:
        description: packagecloud repository to publish .deb.
        required: false
        type: string
        default: ''
    secrets:
      PYPI_TOKEN:
        required: false
      PACKAGECLOUD_TOKEN:
        required: false
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: piotrpawlaczek/python-blacken@v22.3.0
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
      - uses: py-actions/flake8@v2.3.0
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        if: inputs.mypy
      - uses: actions/setup-python@v5.0.0
        if: inputs.mypy
      - run: |
          python -m venv venv
          source ./venv/bin/activate
        if: inputs.mypy
      - run: python -m pip install -r requirements.txt || true
        if: inputs.mypy
      - run: python -m pip install mypy
        if: inputs.mypy
      - run: mypy
        if: inputs.mypy
  install:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
        include:
          - python-version: "3.11"
            upload: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install build twine --user
      - run: python -m build --sdist --wheel --outdir dist/
      - run: twine check dist/*
      - run: python3 -m pip install .
      - uses: actions/upload-artifact@v4.3.1
        if: matrix.upload
        with:
          name: build
          path: dist/*
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        if: inputs.docs
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
        if: inputs.docs
      - run: |
          python -m venv venv
          source ./venv/bin/activate
          python -m pip install sphinx
          python -m pip install -r docs/requirements.txt || true
          sphinx-build -b html docs/ docs/_build
        if: inputs.docs
      - uses: actions/upload-artifact@v4.3.1
        if: inputs.docs
        with:
          name: docs
          path: docs/_build/
  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        if: inputs.deb
      - id: version
        if: inputs.deb
        uses: docker://lpenz/ghaction-version-gen:0.13.6
      - uses: docker://lpenz/ghaction-python-stdeb:0.3
        if: inputs.deb
        with:
          debian_revision: ${{ steps.version.outputs.distance }}
      - uses: actions/upload-artifact@v4.3.1
        if: inputs.deb
        with:
          name: deb
          if-no-files-found: error
          path: '*.deb'
  pytest:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: lpenz/ghaction-pytest-cov@v1
      - uses: coverallsapp/github-action@v2.2.3
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  coverage-finish:
    if: inputs.coveralls
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2.2.3
        with:
          parallel-finished: true
  publish-packagecloud:
    needs: [ black, flake8, mypy, install, docs, deb, pytest ]
    if: inputs.publish_packagecloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ fromJson(inputs.publish_packagecloud_repository) }}
    steps:
      - uses: actions/checkout@v4.1.1
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.13.6
      - name: download deb
        uses: actions/download-artifact@v4.1.2
        if: inputs.deb
        with:
          name: deb
      - name: publish deb on packagecloud
        uses: docker://lpenz/ghaction-packagecloud:0.4
        if: steps.version.outputs.version_commit != ''
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        with:
          repository: ${{ matrix.repository }}
  publish-pypi:
    needs: [ black, flake8, mypy, install, docs, deb, pytest ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.13.6
      - run: python -m pip install build --user
      - run: python -m build --sdist --wheel --outdir dist/
      - uses: pypa/gh-action-pypi-publish@v1.8.11
        if: steps.version.outputs.version_tagged != ''
        with:
          password: ${{ secrets.PYPI_TOKEN }}
  publish-github-release:
    needs: [ black, flake8, mypy, install, docs, deb, pytest ]
    if: inputs.publish_github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.13.6
      - name: download deb
        uses: actions/download-artifact@v4.1.2
        if: inputs.deb
        with:
          name: deb
          path: deb
      - name: download build
        uses: actions/download-artifact@v4.1.2
        with:
          name: build
          path: build
      - name: list all files
        run: find . -type f
      - name: publish github release with .deb
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: inputs.deb && steps.version.outputs.version_tagged != ''
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            deb/*.deb
            build/*
            ${{ inputs.publish_github_release_files }}
      - name: publish github release without .deb
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: "!inputs.deb && steps.version.outputs.version_tagged != ''"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            build/*
            ${{ inputs.publish_github_release_files }}
